version: '3.7'

services:
  node_backend:
    container_name: node_server
    build:
      context: .
    ports:
      - "80:3000"
    environment:
      - PGDATABASE=postgres_db
      - PGUSER=user
      - PGPASSWORD=12345
      - PGHOST=node_db
    depends_on:
      - node_db
    networks:
      - awesome
  node_db:
    container_name: node_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres_db
    volumes:
      - nps_data:/var/lib/postgresql/data
    networks:
      - awesome
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=secret
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "8081:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - node_db
    networks:
      - awesome

volumes:
  nps_data: {}
  pgadmin-data: {}
networks:
  awesome:
    driver: bridge
